from pathlib import Path
from typing import Any, Dict, List


class PowerBIProjectBuilder:
    """
    Builds the generated Power BI project files on disk.

    Takes the logical project generated by
    PowerBIProjectGenerationAgent and writes the
    files into:

        backend/generated_projects/<project_name>/
    """

    def __init__(self):
        self.base_directory = (
            Path(__file__).resolve().parents[2]
            / "generated_projects"
        )

    def build(
        self,
        project_name: str,
        files: List[Dict[str, Any]]
    ) -> Dict[str, Any]:

        project_directory = (
            self.base_directory / project_name
        )

        # Create project directory
        project_directory.mkdir(
            parents=True,
            exist_ok=True
        )

        created_files = []

        for file_info in files:

            relative_path = file_info.get("path")
            content = file_info.get("content", "")

            if not relative_path:
                continue

            file_path = (
                project_directory / relative_path
            )

            # Create parent directories
            file_path.parent.mkdir(
                parents=True,
                exist_ok=True
            )

            # Write file
            file_path.write_text(
                content,
                encoding="utf-8"
            )

            created_files.append(
                str(file_path)
            )

        return {
            "status": "built",
            "project_directory": str(project_directory),
            "files_created": len(created_files),
            "created_files": created_files
        }