from typing import Any, Dict, List

import pandas as pd


class AnalysisExecutionAgent:
    """
    Module 5.5 — Analysis Execution Agent

    Executes the analysis plan generated by the
    AnalysisPlanAgent against the uploaded dataset.

    Input:
        DataFrame
        Analysis plan

    Output:
        Structured analysis results that can be consumed
        by the InsightGenerationAgent.
    """

    def __init__(self):
        pass

    # =====================================================
    # MAIN EXECUTION FUNCTION
    # =====================================================

    def execute(
        self,
        dataframe: pd.DataFrame,
        analysis_plan: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:

        results = []

        if dataframe is None:
            return results

        if dataframe.empty:
            return results

        for step in analysis_plan:

            metric = step.get("metric")
            aggregation = step.get("aggregation")
            group_by = step.get("group_by")
            time_granularity = step.get(
                "time_granularity"
            )
            analysis_type = step.get(
                "analysis_type"
            )

            # -------------------------------------------------
            # Validate metric
            # -------------------------------------------------

            if not metric:
                continue

            if metric not in dataframe.columns:
                continue

            # -------------------------------------------------
            # Validate aggregation
            # -------------------------------------------------

            aggregation = self._normalize_aggregation(
                aggregation
            )

            # -------------------------------------------------
            # No grouping
            # -------------------------------------------------

            if not group_by:

                result = self._execute_without_grouping(
                    dataframe,
                    metric,
                    aggregation,
                    analysis_type
                )

                if result:
                    results.append(result)

                continue

            # -------------------------------------------------
            # Validate grouping column
            # -------------------------------------------------

            if group_by not in dataframe.columns:
                continue

            # -------------------------------------------------
            # Date grouping
            # -------------------------------------------------

            if time_granularity:

                result = self._execute_time_analysis(
                    dataframe,
                    metric,
                    aggregation,
                    group_by,
                    time_granularity,
                    analysis_type
                )

                if result:
                    results.append(result)

                continue

            # -------------------------------------------------
            # Categorical grouping
            # -------------------------------------------------

            result = self._execute_category_analysis(
                dataframe,
                metric,
                aggregation,
                group_by,
                analysis_type
            )

            if result:
                results.append(result)

        return results

    # =====================================================
    # AGGREGATION NORMALIZATION
    # =====================================================

    def _normalize_aggregation(
        self,
        aggregation: str
    ) -> str:

        if not aggregation:
            return "sum"

        aggregation = str(
            aggregation
        ).lower().strip()

        allowed = {
            "sum",
            "mean",
            "average",
            "avg",
            "min",
            "max",
            "count"
        }

        if aggregation not in allowed:
            return "sum"

        if aggregation in {
            "mean",
            "average",
            "avg"
        }:
            return "mean"

        return aggregation

    # =====================================================
    # WITHOUT GROUPING
    # =====================================================

    def _execute_without_grouping(
        self,
        dataframe: pd.DataFrame,
        metric: str,
        aggregation: str,
        analysis_type: str
    ) -> Dict[str, Any]:

        series = pd.to_numeric(
            dataframe[metric],
            errors="coerce"
        ).dropna()

        if series.empty:
            return {}

        value = self._aggregate_series(
            series,
            aggregation
        )

        return {
            "step": None,
            "analysis_type": analysis_type,
            "metric": metric,
            "aggregation": aggregation,
            "group_by": None,
            "time_granularity": None,
            "rows": [
                {
                    metric: value
                }
            ]
        }

    # =====================================================
    # TIME ANALYSIS
    # =====================================================

    def _execute_time_analysis(
        self,
        dataframe: pd.DataFrame,
        metric: str,
        aggregation: str,
        group_by: str,
        time_granularity: str,
        analysis_type: str
    ) -> Dict[str, Any]:

        working_df = dataframe.copy()

        # -------------------------------------------------
        # Convert date column
        # -------------------------------------------------

        working_df[group_by] = pd.to_datetime(
            working_df[group_by],
            errors="coerce"
        )

        working_df = working_df.dropna(
            subset=[group_by]
        )

        if working_df.empty:
            return {}

        # -------------------------------------------------
        # Convert metric to numeric
        # -------------------------------------------------

        working_df[metric] = pd.to_numeric(
            working_df[metric],
            errors="coerce"
        )

        working_df = working_df.dropna(
            subset=[metric]
        )

        if working_df.empty:
            return {}

        # -------------------------------------------------
        # Normalize granularity
        # -------------------------------------------------

        granularity = str(
            time_granularity or "month"
        ).lower()

        if granularity == "year":

            working_df["_period"] = (
                working_df[group_by]
                .dt.to_period("Y")
                .astype(str)
            )

        elif granularity == "quarter":

            working_df["_period"] = (
                working_df[group_by]
                .dt.to_period("Q")
                .astype(str)
            )

        elif granularity == "week":

            working_df["_period"] = (
                working_df[group_by]
                .dt.to_period("W")
                .astype(str)
            )

        elif granularity == "day":

            working_df["_period"] = (
                working_df[group_by]
                .dt.strftime("%Y-%m-%d")
            )

        else:

            # Default = month

            working_df["_period"] = (
                working_df[group_by]
                .dt.to_period("M")
                .astype(str)
            )

        # -------------------------------------------------
        # Aggregate
        # -------------------------------------------------

        grouped = (
            working_df
            .groupby("_period")[metric]
            .agg(aggregation)
            .reset_index()
        )

        # -------------------------------------------------
        # Sort chronologically
        # -------------------------------------------------

        grouped = grouped.sort_values(
            "_period"
        )

        rows = []

        for _, row in grouped.iterrows():

            rows.append({
                group_by: row["_period"],
                metric: float(row[metric])
            })

        return {
            "step": None,
            "analysis_type": analysis_type,
            "metric": metric,
            "aggregation": aggregation,
            "group_by": group_by,
            "time_granularity": granularity,
            "rows": rows
        }

    # =====================================================
    # CATEGORY ANALYSIS
    # =====================================================

    def _execute_category_analysis(
        self,
        dataframe: pd.DataFrame,
        metric: str,
        aggregation: str,
        group_by: str,
        analysis_type: str
    ) -> Dict[str, Any]:

        working_df = dataframe.copy()

        # -------------------------------------------------
        # Convert metric
        # -------------------------------------------------

        working_df[metric] = pd.to_numeric(
            working_df[metric],
            errors="coerce"
        )

        working_df = working_df.dropna(
            subset=[metric]
        )

        if working_df.empty:
            return {}

        # -------------------------------------------------
        # Remove missing categories
        # -------------------------------------------------

        working_df = working_df.dropna(
            subset=[group_by]
        )

        if working_df.empty:
            return {}

        # -------------------------------------------------
        # Aggregate
        # -------------------------------------------------

        grouped = (
            working_df
            .groupby(group_by)[metric]
            .agg(aggregation)
            .reset_index()
        )

        # -------------------------------------------------
        # Sort descending
        # -------------------------------------------------

        grouped = grouped.sort_values(
            metric,
            ascending=False
        )

        rows = []

        for _, row in grouped.iterrows():

            value = row[metric]

            if pd.isna(value):
                continue

            rows.append({
                group_by: row[group_by],
                metric: float(value)
            })

        return {
            "step": None,
            "analysis_type": analysis_type,
            "metric": metric,
            "aggregation": aggregation,
            "group_by": group_by,
            "time_granularity": None,
            "rows": rows
        }

    # =====================================================
    # SERIES AGGREGATION
    # =====================================================

    def _aggregate_series(
        self,
        series: pd.Series,
        aggregation: str
    ) -> float:

        if aggregation == "sum":
            return float(series.sum())

        if aggregation == "mean":
            return float(series.mean())

        if aggregation == "min":
            return float(series.min())

        if aggregation == "max":
            return float(series.max())

        if aggregation == "count":
            return float(series.count())

        return float(series.sum())